sonar.projectKey=Ramo170_vendeai
sonar.organization=ramo170

# Pastas de código de produção
sonar.sources=backend/src

# Pastas de testes (excluindo os arquivos de spec de dentro do src, ou apontando para a pasta test)
sonar.tests=backend/src,backend/test

# Onde procurar os relatórios de cobertura do lcov
sonar.javascript.lcov.reportPaths=backend/coverage/lcov.info

# Exclusões gerais
sonar.exclusions=**/node_modules/**,**/dist/**,**/.next/**,**/coverage/**,**/*.spec.ts,**/*.test.ts

# Garante que apenas os arquivos de teste sejam considerados testes
sonar.test.inclusions=**/*.spec.ts,**/*.test.ts