sonar.projectKey=Ramo170_vendeai
sonar.organization=ramo170

sonar.sources=backend/src
sonar.tests=backend

sonar.test.inclusions=**/*.spec.ts

sonar.exclusions=**/node_modules/**,**/dist/**,**/.next/**,**/coverage/**

sonar.javascript.lcov.reportPaths=backend/coverage/lcov.info